using KH2AiTutorWeb.Helpers;
using OpenKh.Kh2Bdx.Models;
using System.Linq;
using System.Text.RegularExpressions;

namespace KH2AiTutorWeb.Usecases
{
    public class QueryTrapsUsecase
    {
        private readonly IDictionary<string, string> _thundrioRefs = FromThundrioKhKh2AiDecomp();

        public IEnumerable<TrapHrefNode> GetAllInTreeStyle()
        {
            var traps = BdxTraps.GetTraps()
                .OrderBy(trap => trap.Name);

            var trapsLevel1 = traps
                .GroupBy(trap => trap.Name.Split('_')[0]);

            IEnumerable<HrefAndDisplay> GetReferencesOf(BdxTrap trap)
            {
                if (_thundrioRefs.TryGetValue(trap.Name, out string? href))
                {
                    yield return new HrefAndDisplay(href, "thundrio");
                }
            }

            return trapsLevel1
                .Select(
                    group1 => new TrapHrefNode(
                        References: Array.Empty<HrefAndDisplay>(),
                        Display: group1.Key,
                        Children: group1
                            .GroupBy(trap => string.Join("_", trap.Name.Split('_').Take(2)))
                            .Select(
                                group2 => new TrapHrefNode(
                                    References: Array.Empty<HrefAndDisplay>(),
                                    Display: group2.Key,
                                    Children: group2
                                        .Select(
                                            trap => new TrapHrefNode(
                                                References: GetReferencesOf(trap),
                                                Display: trap.Name,
                                                Children: Array.Empty<TrapHrefNode>()
                                            )
                                        )
                                )
                            )
                    )
                );
        }

        private static readonly string _thundrioFiles = @"bdscript-pseudocode/README.md
formatted_docs/kn/tarp_friend_is_equiped_ability.md
formatted_docs/kn/trap_attack_is_finish.md
formatted_docs/kn/trap_btlobj_is_reflect_motion.md
formatted_docs/kn/trap_chickenlittle_get_nearest_target.md
formatted_docs/kn/trap_chickenlittle_get_shoot_target.md
formatted_docs/kn/trap_chickenlittle_set_shoot_target.md
formatted_docs/kn/trap_enemy_is_attacked_from.md
formatted_docs/kn/trap_friend_action_clear.md
formatted_docs/kn/trap_friend_add_warp_point.md
formatted_docs/kn/trap_friend_add_watch_effect.md
formatted_docs/kn/trap_friend_disable_follow_enemy.md
formatted_docs/kn/trap_friend_disable_follow_player.md
formatted_docs/kn/trap_friend_disable_inertia.md
formatted_docs/kn/trap_friend_enable_follow_enemy.md
formatted_docs/kn/trap_friend_enable_follow_player.md
formatted_docs/kn/trap_friend_enable_inertia.md
formatted_docs/kn/trap_friend_end_limit.md
formatted_docs/kn/trap_friend_follow_enemy.md
formatted_docs/kn/trap_friend_follow_player.md
formatted_docs/kn/trap_friend_get_action_param.md
formatted_docs/kn/trap_friend_get_player_attacker.md
formatted_docs/kn/trap_friend_get_target_last_position.md
formatted_docs/kn/trap_friend_invalidate_warp_point.md
formatted_docs/kn/trap_friend_is_control.md
formatted_docs/kn/trap_friend_is_effect_exist.md
formatted_docs/kn/trap_friend_is_moveonly.md
formatted_docs/kn/trap_friend_is_start_leave.md
formatted_docs/kn/trap_friend_link_magic.md
formatted_docs/kn/trap_friend_remove_player_attacker.md
formatted_docs/kn/trap_friend_set_target.md
formatted_docs/kn/trap_friend_start_leave.md
formatted_docs/kn/trap_friend_start_limit.md
formatted_docs/kn/trap_friend_use_item.md
formatted_docs/kn/trap_genie_change_form.md
formatted_docs/kn/trap_genie_get_limit_command.md
formatted_docs/kn/trap_obj_is_motion_sync.md
formatted_docs/kn/trap_obj_is_tornado.md
formatted_docs/kn/trap_obj_reset_special_command.md
formatted_docs/kn/trap_obj_set_special_command.md
formatted_docs/kn/trap_obj_set_stop_timer.md
formatted_docs/kn/trap_obj_set_use_mp.md
formatted_docs/kn/trap_peterpan_accept_notify_player_target.md
formatted_docs/kn/trap_peterpan_receive_notify_player_target.md
formatted_docs/kn/trap_sheet_get_drive_time.md
formatted_docs/kn/trap_sheet_get_mp.md
formatted_docs/kn/trap_stitch_effect_kill.md
formatted_docs/kn/trap_stitch_effect_start.md
formatted_docs/kn/trap_stitch_get_screen_position.md
formatted_docs/kn/trap_stitch_move_request.md
formatted_docs/kn/trap_stitch_set_screen_position.md
formatted_docs/kn/trap_stitch_shot_effect.md
formatted_docs/kn/trap_sysobj_is_blow.md
formatted_docs/kn/trap_sysobj_is_boss.md
formatted_docs/kn/trap_sysobj_is_finish_blow.md
formatted_docs/kn/trap_sysobj_is_limit.md
formatted_docs/kn/trap_sysobj_is_summon.md
formatted_docs/kn/trap_sysobj_is_zako.md
formatted_docs/kn/trap_sysobj_motion_cont_push.md
formatted_docs/kn/trap_target_searcher_set_check_hide_from_friend.md
formatted_docs/ryj/trap_camera_apply_inverse_pos.md
formatted_docs/ryj/trap_obj_set_xyzrot.md
formatted_docs/ryj/trap_obj_target_radius.md
formatted_docs/ryj/trap_player_push_ability_button.md
formatted_docs/ryj/trap_special_last_xemnus_laser_attack.md
formatted_docs/ryj/trap_special_last_xemnus_laser_end.md
formatted_docs/ryj/trap_special_last_xemnus_laser_optimize.md
formatted_docs/ryj/trap_special_last_xemnus_laser_optimize_end.md
formatted_docs/ryj/trap_special_last_xemnus_laser_start.md
formatted_docs/Ti/trap_check_rtn_option_flag.md
formatted_docs/Ti/trap_clear_active_path.md
formatted_docs/Ti/trap_create_active_path.md
formatted_docs/Ti/trap_eh22_path_get_point.md
formatted_docs/Ti/trap_eh22_path_is_moving.md
formatted_docs/Ti/trap_eh22_path_move_before.md
formatted_docs/Ti/trap_eh22_path_move_next.md
formatted_docs/Ti/trap_eh22_path_play.md
formatted_docs/Ti/trap_end_rtn_action.md
formatted_docs/Ti/trap_forward_path_current_pointer.md
formatted_docs/Ti/trap_get_obj_head_pos.md
formatted_docs/Ti/trap_get_path_current_dir.md
formatted_docs/Ti/trap_get_path_current_pos.md
formatted_docs/Ti/trap_get_path_dir.md
formatted_docs/Ti/trap_get_path_dir_from_obj.md
formatted_docs/Ti/trap_get_path_dir_r.md
formatted_docs/Ti/trap_get_path_first_point_pos.md
formatted_docs/Ti/trap_get_path_last_point_pos.md
formatted_docs/Ti/trap_get_path_point_pos.md
formatted_docs/Ti/trap_get_rtn_action.md
formatted_docs/Ti/trap_get_rtn_action_dir.md
formatted_docs/Ti/trap_get_start_rtn_action.md
formatted_docs/Ti/trap_is_end_rtn_action.md
formatted_docs/Ti/trap_is_rtn_change_dir.md
formatted_docs/Ti/trap_reset_active_path.md
formatted_docs/Ti/trap_reset_leave_way.md
formatted_docs/Ti/trap_reset_path_current_pointer.md
formatted_docs/Ti/trap_reverse_path_way.md
formatted_docs/Ti/trap_set_path_by_group.md
formatted_docs/Ti/trap_set_path_by_id.md
formatted_docs/Ti/trap_set_path_target_point.md
formatted_docs/Ti/trap_set_path_way.md
formatted_docs/Ti/trap_set_rtn_option_flag.md
formatted_docs/Ti/trap_set_rtn_partner.md
formatted_docs/Ti/trap_set_rtn_time_param.md
formatted_docs/toc.md
formatted_docs/trap_empty_func.md
formatted_docs/trap_enemy_add_damage.md
formatted_docs/trap_obj_scatter_prize_tt.md
formatted_docs/trap_obj_set_detach_callback.md
formatted_docs/Ts/trap_attack_hit_mark_pos.md
formatted_docs/Ts/trap_attack_set_rc_owner.md
formatted_docs/Ts/trap_attack_set_reaction_offset.md
formatted_docs/Ts/trap_bghit_check_line.md
formatted_docs/Ts/trap_bghit_get_cross_pos.md
formatted_docs/Ts/trap_bghit_get_kind.md
formatted_docs/Ts/trap_bghit_get_normal.md
formatted_docs/Ts/trap_bghit_is_hit.md
formatted_docs/Ts/trap_camera_shake.md
formatted_docs/Ts/trap_card_set_spec.md
formatted_docs/Ts/trap_command_limit_trinity_commbo_start.md
formatted_docs/Ts/trap_dice_set_spec.md
formatted_docs/Ts/trap_enemy_stop_all_end.md
formatted_docs/Ts/trap_enemy_stop_all_start.md
formatted_docs/Ts/trap_enemy_summon_entry.md
formatted_docs/Ts/trap_flare_free.md
formatted_docs/Ts/trap_flare_get_pos.md
formatted_docs/Ts/trap_flare_init.md
formatted_docs/Ts/trap_flare_is_empty.md
formatted_docs/Ts/trap_flare_new.md
formatted_docs/Ts/trap_flare_set_effect.md
formatted_docs/Ts/trap_flare_set_pos.md
formatted_docs/Ts/trap_flare_set_radius.md
formatted_docs/Ts/trap_flare_set_target.md
formatted_docs/Ts/trap_friend_call.md
formatted_docs/Ts/trap_friend_disable_system_wishdir.md
formatted_docs/Ts/trap_friend_enable_system_wishdir.md
formatted_docs/Ts/trap_friend_force_warp.md
formatted_docs/Ts/trap_friend_get.md
formatted_docs/Ts/trap_friend_get_current_action.md
formatted_docs/Ts/trap_friend_get_main_status.md
formatted_docs/Ts/trap_friend_get_target_size.md
formatted_docs/Ts/trap_friend_set_script_status.md
formatted_docs/Ts/trap_friend_set_warp_level.md
formatted_docs/Ts/trap_friend_update_target.md
formatted_docs/Ts/trap_larxene_dead.md
formatted_docs/Ts/trap_limit_aladdin_exclamation_mark_pos.md
formatted_docs/Ts/trap_limit_aladdin_prize_drain.md
formatted_docs/Ts/trap_limit_reset_hit_counter.md
formatted_docs/Ts/trap_limit_start_command.md
formatted_docs/Ts/trap_lockon_hide.md
formatted_docs/Ts/trap_lockon_show.md
formatted_docs/Ts/trap_magic_calc_speed.md
formatted_docs/Ts/trap_obj_act_child_push.md
formatted_docs/Ts/trap_obj_attach_camera.md
formatted_docs/Ts/trap_obj_carpet_obj_idle.md
formatted_docs/Ts/trap_obj_clear_hitback.md
formatted_docs/Ts/trap_obj_detach_camera.md
formatted_docs/Ts/trap_obj_fadeout_se.md
formatted_docs/Ts/trap_obj_get_bg_press.md
formatted_docs/Ts/trap_obj_hide_shadow.md
formatted_docs/Ts/trap_obj_hop_direct.md
formatted_docs/Ts/trap_obj_is_attach_camera.md
formatted_docs/Ts/trap_obj_is_damage_motion.md
formatted_docs/Ts/trap_obj_is_hit_attack.md
formatted_docs/Ts/trap_obj_is_hook.md
formatted_docs/Ts/trap_obj_is_stop.md
formatted_docs/Ts/trap_obj_limit_hover.md
formatted_docs/Ts/trap_obj_limit_hover_set_spec.md
formatted_docs/Ts/trap_obj_limit_mulan_idle.md
formatted_docs/Ts/trap_obj_limit_peterpan_idle.md
formatted_docs/Ts/trap_obj_limit_riku_idle.md
formatted_docs/Ts/trap_obj_near_parts.md
formatted_docs/Ts/trap_obj_party_attack.md
formatted_docs/Ts/trap_obj_play_se_loop.md
formatted_docs/Ts/trap_obj_rc_stop_all.md
formatted_docs/Ts/trap_obj_restart.md
formatted_docs/Ts/trap_obj_set_scissoring.md
formatted_docs/Ts/trap_obj_set_stealth_color.md
formatted_docs/Ts/trap_obj_show_shadow.md
formatted_docs/Ts/trap_obj_stop.md
formatted_docs/Ts/trap_obj_stop_end_all.md
formatted_docs/Ts/trap_obj_stop_start.md
formatted_docs/Ts/trap_obj_tt_ball_blow.md
formatted_docs/Ts/trap_player_card.md
formatted_docs/Ts/trap_player_dice.md
formatted_docs/Ts/trap_player_get_form.md
formatted_docs/Ts/trap_prize_appear.md
formatted_docs/Ts/trap_skateboardscore_add_count.md
formatted_docs/Ts/trap_skateboard_edge_jump.md
formatted_docs/Ts/trap_skateboard_ride.md
formatted_docs/Ts/trap_skateboard_ride_edge.md
formatted_docs/Ts/trap_skateboard_trick.md
formatted_docs/Ts/trap_skateboard_trick_motion_push.md
formatted_docs/Ts/trap_status_peterpan_prize_drain_end.md
formatted_docs/Ts/trap_status_peterpan_prize_drain_start.md
formatted_docs/Ts/trap_strike_raid_calc_xyzrot.md
formatted_docs/Ts/trap_summon_is_exec.md
formatted_docs/Ts/trap_target_clear.md
formatted_docs/Ts/trap_target_dist.md
formatted_docs/Ts/trap_target_get_group.md
formatted_docs/Ts/trap_target_searcher_add.md
formatted_docs/Ts/trap_target_searcher_add_target.md
formatted_docs/Ts/trap_target_searcher_get_old.md
formatted_docs/Ts/trap_target_searcher_get_target_num.md
formatted_docs/Ts/trap_target_searcher_init.md
formatted_docs/Ts/trap_target_searcher_reset.md
formatted_docs/Ts/trap_target_searcher_search_obj.md
formatted_docs/Ts/trap_target_seracher_search.md
formatted_docs/Ts/trap_target_set_group.md
formatted_docs/Ts/trap_trinity_shot_ensure.md
formatted_docs/Ts/trap_trinity_shot_init.md
formatted_docs/Ts/trap_trinity_shot_set_effect_id.md
formatted_docs/Ts/trap_trinity_shot_start.md
formatted_docs/Ts/trap_vacuum_set_effective_range.md
formatted_docs/Ts/trap_xemnas_get_obj.md
formatted_docs/YS/func_area_activate_unit.md
formatted_docs/YS/func_bg_barrier_off.md
formatted_docs/YS/func_bg_barrier_on.md
formatted_docs/YS/func_history_clear_enemy.md
formatted_docs/YS/func_obj_control_off.md
formatted_docs/YS/func_obj_control_on.md
formatted_docs/YS/func_screen_whitein.md
formatted_docs/YS/func_screen_whiteout.md
formatted_docs/YS/func_system_set_game_speed.md
formatted_docs/YS/method_blur_init.md
formatted_docs/YS/method_blur_start.md
formatted_docs/YS/method_blur_stop.md
formatted_docs/YS/method_message_is_end.md
formatted_docs/YS/method_obj_disable_collision.md
formatted_docs/YS/method_obj_disable_reaction_command.md
formatted_docs/YS/method_obj_enable_collision.md
formatted_docs/YS/method_obj_enable_reaction_command.md
formatted_docs/YS/method_obj_is_culling.md
formatted_docs/YS/method_obj_jump.md
formatted_docs/YS/method_obj_reset_collision.md
formatted_docs/YS/method_obj_reset_reaction_command.md
formatted_docs/YS/method_vector_scale.md
formatted_docs/YS/trap_abs.md
formatted_docs/YS/trap_absf.md
formatted_docs/YS/trap_act_shout.md
formatted_docs/YS/trap_act_table_add.md
formatted_docs/YS/trap_act_table_init.md
formatted_docs/YS/trap_area_area.md
formatted_docs/YS/trap_area_battle_set.md
formatted_docs/YS/trap_area_cost_ratio.md
formatted_docs/YS/trap_area_cost_rest.md
formatted_docs/YS/trap_area_entrance.md
formatted_docs/YS/trap_area_event_set.md
formatted_docs/YS/trap_area_init.md
formatted_docs/YS/trap_area_jump.md
formatted_docs/YS/trap_area_map_set.md
formatted_docs/YS/trap_area_setjump.md
formatted_docs/YS/trap_area_set_next_entrance.md
formatted_docs/YS/trap_area_set_return_tr.md
formatted_docs/YS/trap_area_world.md
formatted_docs/YS/trap_assert.md
formatted_docs/YS/trap_attack_dup.md
formatted_docs/YS/trap_attack_exec_reflect.md
formatted_docs/YS/trap_attack_free.md
formatted_docs/YS/trap_attack_get_owner.md
formatted_docs/YS/trap_attack_get_param_id.md
formatted_docs/YS/trap_attack_get_reflect_count.md
formatted_docs/YS/trap_attack_get_reflect_vector.md
formatted_docs/YS/trap_attack_get_type.md
formatted_docs/YS/trap_attack_hit_bg_pos.md
formatted_docs/YS/trap_attack_is_hit.md
formatted_docs/YS/trap_attack_is_hit_bg.md
formatted_docs/YS/trap_attack_is_hit_floor.md
formatted_docs/YS/trap_attack_is_hit_wall.md
formatted_docs/YS/trap_attack_is_reflect.md
formatted_docs/YS/trap_attack_is_strike.md
formatted_docs/YS/trap_attack_is_valid.md
formatted_docs/YS/trap_attack_new.md
formatted_docs/YS/trap_attack_new_combo_group.md
formatted_docs/YS/trap_attack_rc_receiver.md
formatted_docs/YS/trap_attack_reflecter.md
formatted_docs/YS/trap_attack_refresh.md
formatted_docs/YS/trap_attack_set_effect.md
formatted_docs/YS/trap_attack_set_hitmark_pos.md
formatted_docs/YS/trap_attack_set_hit_callback.md
formatted_docs/YS/trap_attack_set_line.md
formatted_docs/YS/trap_attack_set_obj_pax.md
formatted_docs/YS/trap_attack_set_pax.md
formatted_docs/YS/trap_attack_set_pos.md
formatted_docs/YS/trap_attack_set_radius.md
formatted_docs/YS/trap_attack_set_rc.md
formatted_docs/YS/trap_attack_set_reflect_callback.md
formatted_docs/YS/trap_attack_set_system_pax.md
formatted_docs/YS/trap_attack_set_team.md
formatted_docs/YS/trap_attack_set_time.md
formatted_docs/YS/trap_attack_strike.md
formatted_docs/YS/trap_bg_cross_pos.md
formatted_docs/YS/trap_bg_get_normal.md
formatted_docs/YS/trap_bg_get_random_pos.md
formatted_docs/YS/trap_bg_get_random_pos_air.md
formatted_docs/YS/trap_bg_ground_pos.md
formatted_docs/YS/trap_bg_hide.md
formatted_docs/YS/trap_bg_is_floor.md
formatted_docs/YS/trap_bg_set_animation_speed.md
formatted_docs/YS/trap_bg_set_belt_conveyor.md
formatted_docs/YS/trap_bg_set_uvscroll_speed.md
formatted_docs/YS/trap_bg_show.md
formatted_docs/YS/trap_bonuslevel_up.md
formatted_docs/YS/trap_btlobj_dup_sheet.md
formatted_docs/YS/trap_btlobj_lockon_target.md
formatted_docs/YS/trap_btlobj_set_sheet.md
formatted_docs/YS/trap_btlobj_target.md
formatted_docs/YS/trap_camera_apply_pos.md
formatted_docs/YS/trap_camera_at.md
formatted_docs/YS/trap_camera_begin_scope.md
formatted_docs/YS/trap_camera_cancel.md
formatted_docs/YS/trap_camera_end_scope.md
formatted_docs/YS/trap_camera_eye.md
formatted_docs/YS/trap_camera_get_projection_pos.md
formatted_docs/YS/trap_camera_reset.md
formatted_docs/YS/trap_camera_set_scope_closeup_distance.md
formatted_docs/YS/trap_camera_set_scope_target_pos.md
formatted_docs/YS/trap_camera_set_scope_zoom.md
formatted_docs/YS/trap_camera_warp.md
formatted_docs/YS/trap_camera_watch.md
formatted_docs/YS/trap_command_cage_off.md
formatted_docs/YS/trap_command_cage_on.md
formatted_docs/YS/trap_command_disable_group.md
formatted_docs/YS/trap_command_enable.md
formatted_docs/YS/trap_command_enable_group.md
formatted_docs/YS/trap_command_enable_item.md
formatted_docs/YS/trap_command_override.md
formatted_docs/YS/trap_command_override_slot.md
formatted_docs/YS/trap_command_override_top.md
formatted_docs/YS/trap_command_set_side_b.md
formatted_docs/YS/trap_command_slot_set_status.md
formatted_docs/YS/trap_damage_attack_param_id.md
formatted_docs/YS/trap_damage_attack_type.md
formatted_docs/YS/trap_damage_blow_speed.md
formatted_docs/YS/trap_damage_blow_up.md
formatted_docs/YS/trap_damage_damage.md
formatted_docs/YS/trap_damage_element.md
formatted_docs/YS/trap_damage_exec_reaction.md
formatted_docs/YS/trap_damage_get_hitback.md
formatted_docs/YS/trap_damage_get_reaction_type.md
formatted_docs/YS/trap_damage_is_cure.md
formatted_docs/YS/trap_damage_is_exec_reaction.md
formatted_docs/YS/trap_damage_is_finish.md
formatted_docs/YS/trap_damage_is_normal.md
formatted_docs/YS/trap_damage_is_reaction.md
formatted_docs/YS/trap_damage_orig_reaction.md
formatted_docs/YS/trap_damage_parts.md
formatted_docs/YS/trap_damage_reaction.md
formatted_docs/YS/trap_effect_add_dead_block.md
formatted_docs/YS/trap_effect_dir.md
formatted_docs/YS/trap_effect_fadeout.md
formatted_docs/YS/trap_effect_is_active.md
formatted_docs/YS/trap_effect_is_alive.md
formatted_docs/YS/trap_effect_kill.md
formatted_docs/YS/trap_effect_loop_end.md
formatted_docs/YS/trap_effect_loop_end_kill.md
formatted_docs/YS/trap_effect_pause.md
formatted_docs/YS/trap_effect_pos.md
formatted_docs/YS/trap_effect_set_color.md
formatted_docs/YS/trap_effect_set_dir.md
formatted_docs/YS/trap_effect_set_pos.md
formatted_docs/YS/trap_effect_set_rot.md
formatted_docs/YS/trap_effect_set_scale.md
formatted_docs/YS/trap_effect_set_type.md
formatted_docs/YS/trap_enemy_count_damager.md
formatted_docs/YS/trap_enemy_each.md
formatted_docs/YS/trap_enemy_exec_damage.md
formatted_docs/YS/trap_enemy_exec_damage_blow.md
formatted_docs/YS/trap_enemy_exec_damage_hitback.md
formatted_docs/YS/trap_enemy_exec_damage_large.md
formatted_docs/YS/trap_enemy_exec_damage_small.md
formatted_docs/YS/trap_enemy_exec_reflect.md
formatted_docs/YS/trap_enemy_get_attacker.md
formatted_docs/YS/trap_enemy_is_damage_motion.md
formatted_docs/YS/trap_enemy_is_no_control.md
formatted_docs/YS/trap_enemy_last_dead.md
formatted_docs/YS/trap_enemy_set_attacker.md
formatted_docs/YS/trap_enemy_set_karma_limit.md
formatted_docs/YS/trap_event_continue_control_off.md
formatted_docs/YS/trap_event_control_off.md
formatted_docs/YS/trap_event_control_on.md
formatted_docs/YS/trap_event_get_rest_time.md
formatted_docs/YS/trap_event_is_exec.md
formatted_docs/YS/trap_event_layer_off.md
formatted_docs/YS/trap_event_layer_on.md
formatted_docs/YS/trap_file_flush.md
formatted_docs/YS/trap_file_is_reading.md
formatted_docs/YS/trap_fixrad.md
formatted_docs/YS/trap_frametime.md
formatted_docs/YS/trap_item_get.md
formatted_docs/YS/trap_item_reduce.md
formatted_docs/YS/trap_jigsaw_get.md
formatted_docs/YS/trap_light_create.md
formatted_docs/YS/trap_light_fadein.md
formatted_docs/YS/trap_light_fadeout.md
formatted_docs/YS/trap_light_set_color.md
formatted_docs/YS/trap_light_set_flag.md
formatted_docs/YS/trap_light_set_fog_far.md
formatted_docs/YS/trap_light_set_fog_max.md
formatted_docs/YS/trap_light_set_fog_min.md
formatted_docs/YS/trap_light_set_fog_near.md
formatted_docs/YS/trap_limit_camera_start.md
formatted_docs/YS/trap_limit_close_gauge.md
formatted_docs/YS/trap_limit_effect_start.md
formatted_docs/YS/trap_limit_effect_start_bind.md
formatted_docs/YS/trap_limit_effect_start_pos.md
formatted_docs/YS/trap_limit_friend.md
formatted_docs/YS/trap_limit_light.md
formatted_docs/YS/trap_limit_motion_start.md
formatted_docs/YS/trap_limit_player.md
formatted_docs/YS/trap_limit_reference.md
formatted_docs/YS/trap_limit_reset_special_command.md
formatted_docs/YS/trap_limit_start_thread.md
formatted_docs/YS/trap_limit_time.md
formatted_docs/YS/trap_magic_can_add_cost.md
formatted_docs/YS/trap_magic_set_cost.md
formatted_docs/YS/trap_magic_start_thread.md
formatted_docs/YS/trap_memory_alloc.md
formatted_docs/YS/trap_memory_free.md
formatted_docs/YS/trap_menuflag_check.md
formatted_docs/YS/trap_menuflag_reset.md
formatted_docs/YS/trap_menuflag_set.md
formatted_docs/YS/trap_message_close.md
formatted_docs/YS/trap_message_open.md
formatted_docs/YS/trap_mission_activate2d.md
formatted_docs/YS/trap_mission_add_combo_counter.md
formatted_docs/YS/trap_mission_add_count.md
formatted_docs/YS/trap_mission_add_gauge.md
formatted_docs/YS/trap_mission_cancel_pause_timer.md
formatted_docs/YS/trap_mission_complete.md
formatted_docs/YS/trap_mission_deactivate2d.md
formatted_docs/YS/trap_mission_dead_boss.md
formatted_docs/YS/trap_mission_decrement_count.md
formatted_docs/YS/trap_mission_disable_count.md
formatted_docs/YS/trap_mission_disable_timer.md
formatted_docs/YS/trap_mission_disable_watch.md
formatted_docs/YS/trap_mission_exit.md
formatted_docs/YS/trap_mission_failed.md
formatted_docs/YS/trap_mission_get_combo_counter.md
formatted_docs/YS/trap_mission_get_count.md
formatted_docs/YS/trap_mission_get_gauge_ratio.md
formatted_docs/YS/trap_mission_get_gauge_warning_ratio.md
formatted_docs/YS/trap_mission_get_max_combo_counter.md
formatted_docs/YS/trap_mission_get_timer.md
formatted_docs/YS/trap_mission_get_timer_second.md
formatted_docs/YS/trap_mission_increment_count.md
formatted_docs/YS/trap_mission_information.md
formatted_docs/YS/trap_mission_is_activate2d.md
formatted_docs/YS/trap_mission_is_gauge_warning.md
formatted_docs/YS/trap_mission_is_lock.md
formatted_docs/YS/trap_mission_lock.md
formatted_docs/YS/trap_mission_pause_timer.md
formatted_docs/YS/trap_mission_reset_pause_mode.md
formatted_docs/YS/trap_mission_reset_warning_count.md
formatted_docs/YS/trap_mission_restart_timer.md
formatted_docs/YS/trap_mission_return.md
formatted_docs/YS/trap_mission_set_combo_counter_param.md
formatted_docs/YS/trap_mission_set_combo_counter_warning_se.md
formatted_docs/YS/trap_mission_set_count.md
formatted_docs/YS/trap_mission_set_count_figure_num.md
formatted_docs/YS/trap_mission_set_count_param.md
formatted_docs/YS/trap_mission_set_gauge.md
formatted_docs/YS/trap_mission_set_gauge_param.md
formatted_docs/YS/trap_mission_set_gauge_ratio.md
formatted_docs/YS/trap_mission_set_max_combo_counter.md
formatted_docs/YS/trap_mission_set_timer_param.md
formatted_docs/YS/trap_mission_set_warning_se.md
formatted_docs/YS/trap_mission_set_watch.md
formatted_docs/YS/trap_mission_start_combo_counter.md
formatted_docs/YS/trap_mission_stop_combo_counter.md
formatted_docs/YS/trap_mission_warning_combo_counter.md
formatted_docs/YS/trap_mission_warning_count.md
formatted_docs/YS/trap_mission_warning_gauge.md
formatted_docs/YS/trap_mission_warning_timer.md
formatted_docs/YS/trap_obj_action_lightcycle.md
formatted_docs/YS/trap_obj_act_clear.md
formatted_docs/YS/trap_obj_act_push.md
formatted_docs/YS/trap_obj_act_shout.md
formatted_docs/YS/trap_obj_act_start.md
formatted_docs/YS/trap_obj_act_start_pri.md
formatted_docs/YS/trap_obj_act_wedge.md
formatted_docs/YS/trap_obj_add_hp.md
formatted_docs/YS/trap_obj_apply_bone_matrix.md
formatted_docs/YS/trap_obj_attach.md
formatted_docs/YS/trap_obj_blow.md
formatted_docs/YS/trap_obj_camera_start.md
formatted_docs/YS/trap_obj_camera_start_global.md
formatted_docs/YS/trap_obj_can_capture_control.md
formatted_docs/YS/trap_obj_can_decide_command.md
formatted_docs/YS/trap_obj_can_look.md
formatted_docs/YS/trap_obj_can_look_pos.md
formatted_docs/YS/trap_obj_can_see.md
formatted_docs/YS/trap_obj_capture_command.md
formatted_docs/YS/trap_obj_check_flag.md
formatted_docs/YS/trap_obj_check_step.md
formatted_docs/YS/trap_obj_clear_occ.md
formatted_docs/YS/trap_obj_cmp.md
formatted_docs/YS/trap_obj_count_entry.md
formatted_docs/YS/trap_obj_dead.md
formatted_docs/YS/trap_obj_dead_mark.md
formatted_docs/YS/trap_obj_detach.md
formatted_docs/YS/trap_obj_dir.md
formatted_docs/YS/trap_obj_disable_occ.md
formatted_docs/YS/trap_obj_disable_occ_bone.md
formatted_docs/YS/trap_obj_dump.md
formatted_docs/YS/trap_obj_each_all.md
formatted_docs/YS/trap_obj_effect_kill_all.md
formatted_docs/YS/trap_obj_effect_start.md
formatted_docs/YS/trap_obj_effect_start_bind.md
formatted_docs/YS/trap_obj_effect_start_bind_other.md
formatted_docs/YS/trap_obj_effect_start_pos.md
formatted_docs/YS/trap_obj_effect_unbind.md
formatted_docs/YS/trap_obj_enable_occ.md
formatted_docs/YS/trap_obj_enable_occ_bone.md
formatted_docs/YS/trap_obj_exec_fall.md
formatted_docs/YS/trap_obj_exec_land.md
formatted_docs/YS/trap_obj_float_height.md
formatted_docs/YS/trap_obj_fly.md
formatted_docs/YS/trap_obj_flyjump.md
formatted_docs/YS/trap_obj_fly_to_jump.md
formatted_docs/YS/trap_obj_get_action.md
formatted_docs/YS/trap_obj_get_appear_way.md
formatted_docs/YS/trap_obj_get_entry_id.md
formatted_docs/YS/trap_obj_get_lightcycle_movement.md
formatted_docs/YS/trap_obj_get_medal.md
formatted_docs/YS/trap_obj_get_moved.md
formatted_docs/YS/trap_obj_get_move_to_space_pos.md
formatted_docs/YS/trap_obj_get_path_movement.md
formatted_docs/YS/trap_obj_get_weight.md
formatted_docs/YS/trap_obj_get_wish_movement.md
formatted_docs/YS/trap_obj_hide.md
formatted_docs/YS/trap_obj_hide_part.md
formatted_docs/YS/trap_obj_history_mark.md
formatted_docs/YS/trap_obj_hitback.md
formatted_docs/YS/trap_obj_hook.md
formatted_docs/YS/trap_obj_hook_command_image.md
formatted_docs/YS/trap_obj_hook_stop.md
formatted_docs/YS/trap_obj_hop.md
formatted_docs/YS/trap_obj_hover.md
formatted_docs/YS/trap_obj_idle.md
formatted_docs/YS/trap_obj_is_action_air.md
formatted_docs/YS/trap_obj_is_act_exec.md
formatted_docs/YS/trap_obj_is_air.md
formatted_docs/YS/trap_obj_is_attach.md
formatted_docs/YS/trap_obj_is_dead.md
formatted_docs/YS/trap_obj_is_entry_fly.md
formatted_docs/YS/trap_obj_is_equip_ability.md
formatted_docs/YS/trap_obj_is_fly.md
formatted_docs/YS/trap_obj_is_history_mark.md
formatted_docs/YS/trap_obj_is_hover.md
formatted_docs/YS/trap_obj_is_jump.md
formatted_docs/YS/trap_obj_is_motion_cancel.md
formatted_docs/YS/trap_obj_is_motion_in_loop.md
formatted_docs/YS/trap_obj_is_pirate_shade.md
formatted_docs/YS/trap_obj_is_ride.md
formatted_docs/YS/trap_obj_is_star.md
formatted_docs/YS/trap_obj_is_unit_active.md
formatted_docs/YS/trap_obj_jump_direct.md
formatted_docs/YS/trap_obj_jump_height_to_uptime.md
formatted_docs/YS/trap_obj_leave.md
formatted_docs/YS/trap_obj_leave_force.md
formatted_docs/YS/trap_obj_levelup_unit.md
formatted_docs/YS/trap_obj_lockon_target.md
formatted_docs/YS/trap_obj_look_end.md
formatted_docs/YS/trap_obj_look_start.md
formatted_docs/YS/trap_obj_look_start_pos.md
formatted_docs/YS/trap_obj_motion_capture.md
formatted_docs/YS/trap_obj_motion_capture_id.md
formatted_docs/YS/trap_obj_motion_check_range.md
formatted_docs/YS/trap_obj_motion_check_trigger.md
formatted_docs/YS/trap_obj_motion_disable_anmatr_effect.md
formatted_docs/YS/trap_obj_motion_enable_anmatr_effect.md
formatted_docs/YS/trap_obj_motion_get_length.md
formatted_docs/YS/trap_obj_motion_get_loop_top.md
formatted_docs/YS/trap_obj_motion_get_time.md
formatted_docs/YS/trap_obj_motion_hook.md
formatted_docs/YS/trap_obj_motion_is_capture.md
formatted_docs/YS/trap_obj_motion_is_hook.md
formatted_docs/YS/trap_obj_motion_is_no_control.md
formatted_docs/YS/trap_obj_motion_speed.md
formatted_docs/YS/trap_obj_motion_sync.md
formatted_docs/YS/trap_obj_motion_unhook.md
formatted_docs/YS/trap_obj_motion_unsync.md
formatted_docs/YS/trap_obj_move_request.md
formatted_docs/YS/trap_obj_move_to_space.md
formatted_docs/YS/trap_obj_part.md
formatted_docs/YS/trap_obj_pattern_disable.md
formatted_docs/YS/trap_obj_pattern_enable.md
formatted_docs/YS/trap_obj_pattern_reset.md
formatted_docs/YS/trap_obj_play_se.md
formatted_docs/YS/trap_obj_pos.md
formatted_docs/YS/trap_obj_reaction_callback.md
formatted_docs/YS/trap_obj_recov_holylight.md
formatted_docs/YS/trap_obj_reraise.md
formatted_docs/YS/trap_obj_reset_command_image.md
formatted_docs/YS/trap_obj_reset_flag.md
formatted_docs/YS/trap_obj_reset_parts_color.md
formatted_docs/YS/trap_obj_reset_pos.md
formatted_docs/YS/trap_obj_reset_stealth.md
formatted_docs/YS/trap_obj_scatter_medal.md
formatted_docs/YS/trap_obj_scatter_prize.md
formatted_docs/YS/trap_obj_scatter_prize_mu.md
formatted_docs/YS/trap_obj_scatter_prize_tr.md
formatted_docs/YS/trap_obj_search_by_camera.md
formatted_docs/YS/trap_obj_search_by_entry.md
formatted_docs/YS/trap_obj_search_by_glance.md
formatted_docs/YS/trap_obj_search_by_part.md
formatted_docs/YS/trap_obj_search_by_serial.md
formatted_docs/YS/trap_obj_search_by_unit_arg.md
formatted_docs/YS/trap_obj_serial.md
formatted_docs/YS/trap_obj_set_act_table.md
formatted_docs/YS/trap_obj_set_bg_collision_type.md
formatted_docs/YS/trap_obj_set_cannon_camera_offset.md
formatted_docs/YS/trap_obj_set_cannon_param.md
formatted_docs/YS/trap_obj_set_dir.md
formatted_docs/YS/trap_obj_set_fall_motion.md
formatted_docs/YS/trap_obj_set_flag.md
formatted_docs/YS/trap_obj_set_jump_motion.md
formatted_docs/YS/trap_obj_set_land_motion.md
formatted_docs/YS/trap_obj_set_medal.md
formatted_docs/YS/trap_obj_set_movement.md
formatted_docs/YS/trap_obj_set_parts_color.md
formatted_docs/YS/trap_obj_set_path.md
formatted_docs/YS/trap_obj_set_player_random_pos.md
formatted_docs/YS/trap_obj_set_pos.md
formatted_docs/YS/trap_obj_set_pos_trans.md
formatted_docs/YS/trap_obj_set_random_pos.md
formatted_docs/YS/trap_obj_set_rot.md
formatted_docs/YS/trap_obj_set_skateboard_mode.md
formatted_docs/YS/trap_obj_set_stealth.md
formatted_docs/YS/trap_obj_set_team.md
formatted_docs/YS/trap_obj_set_unit_arg.md
formatted_docs/YS/trap_obj_shadow_move_end.md
formatted_docs/YS/trap_obj_shadow_move_start.md
formatted_docs/YS/trap_obj_sheet.md
formatted_docs/YS/trap_obj_show.md
formatted_docs/YS/trap_obj_show_part.md
formatted_docs/YS/trap_obj_show_picture.md
formatted_docs/YS/trap_obj_spec.md
formatted_docs/YS/trap_obj_star.md
formatted_docs/YS/trap_obj_start_mpdrive.md
formatted_docs/YS/trap_obj_step_pos.md
formatted_docs/YS/trap_obj_sysjump.md
formatted_docs/YS/trap_obj_target_pos.md
formatted_docs/YS/trap_obj_texanm_start.md
formatted_docs/YS/trap_obj_texanm_stop.md
formatted_docs/YS/trap_obj_tex_fade_set.md
formatted_docs/YS/trap_obj_tex_fade_start.md
formatted_docs/YS/trap_obj_thread_start.md
formatted_docs/YS/trap_obj_touch_zone.md
formatted_docs/YS/trap_obj_turn_dir.md
formatted_docs/YS/trap_obj_unit_arg.md
formatted_docs/YS/trap_obj_unit_group.md
formatted_docs/YS/trap_obj_use_mp.md
formatted_docs/YS/trap_obj_voice.md
formatted_docs/YS/trap_obj_wish_dir.md
formatted_docs/YS/trap_pad_is_button.md
formatted_docs/YS/trap_pad_is_trigger.md
formatted_docs/YS/trap_partram_add_ability.md
formatted_docs/YS/trap_partram_add_ap.md
formatted_docs/YS/trap_partram_add_attack.md
formatted_docs/YS/trap_partram_add_defence.md
formatted_docs/YS/trap_partram_add_wisdom.md
formatted_docs/YS/trap_partram_set_item_max.md
formatted_docs/YS/trap_partram_set_levelup_type.md
formatted_docs/YS/trap_party_get_weapon.md
formatted_docs/YS/trap_party_hand_to_bone.md
formatted_docs/YS/trap_pax_start.md
formatted_docs/YS/trap_pax_start_bind.md
formatted_docs/YS/trap_picture_change.md
formatted_docs/YS/trap_picture_set_pos.md
formatted_docs/YS/trap_player_can_capture_form.md
formatted_docs/YS/trap_player_capture_form.md
formatted_docs/YS/trap_player_capture_form_end.md
formatted_docs/YS/trap_player_get_movement.md
formatted_docs/YS/trap_player_get_rc.md
formatted_docs/YS/trap_player_lockon.md
formatted_docs/YS/trap_player_set_exec_rc.md
formatted_docs/YS/trap_prize_appear_num.md
formatted_docs/YS/trap_prize_appear_tr.md
formatted_docs/YS/trap_prize_appear_xaldin.md
formatted_docs/YS/trap_prize_get_all_tr.md
formatted_docs/YS/trap_prize_num.md
formatted_docs/YS/trap_prize_num_ca.md
formatted_docs/YS/trap_prize_return_ca.md
formatted_docs/YS/trap_prize_vacuum_ca.md
formatted_docs/YS/trap_prize_vacuum_range_ca.md
formatted_docs/YS/trap_progress_check_flag.md
formatted_docs/YS/trap_progress_is_fm_secret_movie.md
formatted_docs/YS/trap_progress_is_second.md
formatted_docs/YS/trap_progress_is_secret_movie.md
formatted_docs/YS/trap_progress_set_flag.md
formatted_docs/YS/trap_putf.md
formatted_docs/YS/trap_puti.md
formatted_docs/YS/trap_puts.md
formatted_docs/YS/trap_random_get.md
formatted_docs/YS/trap_random_getf.md
formatted_docs/YS/trap_random_range.md
formatted_docs/YS/trap_saveflag_check.md
formatted_docs/YS/trap_saveflag_reset.md
formatted_docs/YS/trap_saveflag_set.md
formatted_docs/YS/trap_saveram_get_partram.md
formatted_docs/YS/trap_saveram_increment_friend_recov.md
formatted_docs/YS/trap_saveram_set_form_ability.md
formatted_docs/YS/trap_saveram_set_form_weapon.md
formatted_docs/YS/trap_saveram_set_weapon.md
formatted_docs/YS/trap_score_get.md
formatted_docs/YS/trap_score_score.md
formatted_docs/YS/trap_score_type.md
formatted_docs/YS/trap_score_update.md
formatted_docs/YS/trap_screen_cross_fade.md
formatted_docs/YS/trap_screen_fadein.md
formatted_docs/YS/trap_screen_fadeout.md
formatted_docs/YS/trap_screen_show_picture.md
formatted_docs/YS/trap_sheet_add_munny.md
formatted_docs/YS/trap_sheet_attack_level.md
formatted_docs/YS/trap_sheet_hp.md
formatted_docs/YS/trap_sheet_hp_rate.md
formatted_docs/YS/trap_sheet_level.md
formatted_docs/YS/trap_sheet_max_hp.md
formatted_docs/YS/trap_sheet_min_hp.md
formatted_docs/YS/trap_sheet_munny.md
formatted_docs/YS/trap_sheet_set_attack_level.md
formatted_docs/YS/trap_sheet_set_element_rate.md
formatted_docs/YS/trap_sheet_set_hitback_addition.md
formatted_docs/YS/trap_sheet_set_hp.md
formatted_docs/YS/trap_sheet_set_min_hp.md
formatted_docs/YS/trap_sheet_set_prize_range.md
formatted_docs/YS/trap_signal_call.md
formatted_docs/YS/trap_signal_hook.md
formatted_docs/YS/trap_signal_reserve_hp.md
formatted_docs/YS/trap_signal_reserve_min_hp.md
formatted_docs/YS/trap_sound_disable.md
formatted_docs/YS/trap_sound_play_system.md
formatted_docs/YS/trap_sound_set_bgse_volume.md
formatted_docs/YS/trap_status_begin_free_ability.md
formatted_docs/YS/trap_status_close_pete_curtain.md
formatted_docs/YS/trap_status_end_free_ability.md
formatted_docs/YS/trap_status_force_leave_end.md
formatted_docs/YS/trap_status_force_leave_start.md
formatted_docs/YS/trap_status_hide_shadow.md
formatted_docs/YS/trap_status_is_battle.md
formatted_docs/YS/trap_status_is_force_leave.md
formatted_docs/YS/trap_status_is_mission.md
formatted_docs/YS/trap_status_no_gameover.md
formatted_docs/YS/trap_status_no_leave.md
formatted_docs/YS/trap_status_open_pete_curtain.md
formatted_docs/YS/trap_status_prize_drain_end.md
formatted_docs/YS/trap_status_prize_drain_start.md
formatted_docs/YS/trap_status_secure_mode_end.md
formatted_docs/YS/trap_status_secure_mode_start.md
formatted_docs/YS/trap_status_set_lockon_ratio.md
formatted_docs/YS/trap_status_set_prize_ratio.md
formatted_docs/YS/trap_status_show_shadow.md
formatted_docs/YS/trap_stputf.md
formatted_docs/YS/trap_stputi.md
formatted_docs/YS/trap_stputs.md
formatted_docs/YS/trap_struggle_increment.md
formatted_docs/YS/trap_summon_is_tink_exist.md
formatted_docs/YS/trap_sysobj_appear.md
formatted_docs/YS/trap_sysobj_fadein.md
formatted_docs/YS/trap_sysobj_fadeout.md
formatted_docs/YS/trap_sysobj_is_btlnpc.md
formatted_docs/YS/trap_sysobj_is_exist.md
formatted_docs/YS/trap_sysobj_is_player.md
formatted_docs/YS/trap_sysobj_is_sora.md
formatted_docs/YS/trap_sysobj_motion_change.md
formatted_docs/YS/trap_sysobj_motion_frame_start.md
formatted_docs/YS/trap_sysobj_motion_id.md
formatted_docs/YS/trap_sysobj_motion_is_end.md
formatted_docs/YS/trap_sysobj_motion_push.md
formatted_docs/YS/trap_sysobj_motion_start.md
formatted_docs/YS/trap_sysobj_moveto.md
formatted_docs/YS/trap_sysobj_party.md
formatted_docs/YS/trap_sysobj_player.md
formatted_docs/YS/trap_target_attack.md
formatted_docs/YS/trap_target_clear_after_player.md
formatted_docs/YS/trap_target_clear_before_player.md
formatted_docs/YS/trap_target_dup.md
formatted_docs/YS/trap_target_free.md
formatted_docs/YS/trap_target_is_exist.md
formatted_docs/YS/trap_target_pos.md
formatted_docs/YS/trap_target_search.md
formatted_docs/YS/trap_target_set_after_player.md
formatted_docs/YS/trap_target_set_before_player.md
formatted_docs/YS/trap_target_set_obj.md
formatted_docs/YS/trap_teamwork_alloc.md
formatted_docs/YS/trap_thread_start.md
formatted_docs/YS/trap_timer_count_down.md
formatted_docs/YS/trap_timer_count_up.md
formatted_docs/YS/trap_treasure_get.md
formatted_docs/YS/trap_tutorial_is_open.md
formatted_docs/YS/trap_tutorial_open.md
formatted_docs/YS/trap_tutorial_pause.md
formatted_docs/YS/trap_unit_disable.md
formatted_docs/YS/trap_unit_enable.md
formatted_docs/YS/trap_unit_get_enemy_num.md
formatted_docs/YS/trap_vacuum_create.md
formatted_docs/YS/trap_vacuum_destroy.md
formatted_docs/YS/trap_vacuum_set_dist_rate.md
formatted_docs/YS/trap_vacuum_set_ignore_type.md
formatted_docs/YS/trap_vacuum_set_near_range.md
formatted_docs/YS/trap_vacuum_set_pos.md
formatted_docs/YS/trap_vacuum_set_rot_speed.md
formatted_docs/YS/trap_vacuum_set_speed.md
formatted_docs/YS/trap_vector_add.md
formatted_docs/YS/trap_vector_addf.md
formatted_docs/YS/trap_vector_angle.md
formatted_docs/YS/trap_vector_atan_xz.md
formatted_docs/YS/trap_vector_div.md
formatted_docs/YS/trap_vector_draw.md
formatted_docs/YS/trap_vector_dump.md
formatted_docs/YS/trap_vector_get_rot_xz.md
formatted_docs/YS/trap_vector_homing.md
formatted_docs/YS/trap_vector_inner_prodcut.md
formatted_docs/YS/trap_vector_inter.md
formatted_docs/YS/trap_vector_len.md
formatted_docs/YS/trap_vector_mul.md
formatted_docs/YS/trap_vector_normalize.md
formatted_docs/YS/trap_vector_outer_product.md
formatted_docs/YS/trap_vector_rot.md
formatted_docs/YS/trap_vector_rotx.md
formatted_docs/YS/trap_vector_roty.md
formatted_docs/YS/trap_vector_sub.md
formatted_docs/YS/trap_vector_to_angle.md
formatted_docs/YS/trap_worldflag_check.md
formatted_docs/YS/trap_worldflag_set.md
formatted_docs/YS/trap_worldwork_get.md
instruction_tests/README.md
README.md
syscall_documentation_work_guidelines.md".Replace("\r\n", "\n");

        private static IDictionary<string, string> FromThundrioKhKh2AiDecomp()
        {
            var dict = new SortedDictionary<string, string>();

            var pattern = new Regex("^.+?/(?<name>[^/\\.]+)\\.md$", RegexOptions.Multiline);

            foreach (var match in pattern.Matches(_thundrioFiles).Cast<Match>())
            {
                var line = match.Value.TrimStart('/');
                dict[match.Groups["name"].Value] = $"https://github.com/thundrio-kh/kh2-ai-decomp/blob/master/{line}";
            }

            return dict;
        }
    }
}